# taken from https://rimdev.io/building-net-core-on-travis-ci/
language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
before_script:
 - chmod a+x ./build.sh
script:
 - ./build.sh
before_deploy:
  - ./publish.sh
deploy:
  provider: releases
  api_key:
    secure: 25c4cbb59090ac20ce75b275dba3beb84e368f6b
  file:
    - "FILE 1"
    - "FILE 2"
  skip_cleanup: true
  on:
    tags: true