# taken from https://rimdev.io/building-net-core-on-travis-ci/
language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
before_script:
 - chmod a+x ./build.sh
script:
 - ./build.sh
deploy:
  provider: pypi
  user: sebagomez
  password:
    secure: NRY/9bbPSOcECG4wS6qp32/keTGDSxl0MXOJdSxgCHGxnIExR8y/Hap88E26lmCqL8k48wzxKKREKdMpX64YD/u7nQIgG+oNTzlYFKTR4AJjrm48Qw2Ib0rR+ekh9Jg/F8xe15MtyRJlzhU19rZRHkb4pPgxyxs42B2unbHL4AkwgrhqGJNv9JZl/HeR1fOzkAn6mn1ooaZeKH9rqm3UVtQ2ELfZCqwOHyparK7mDstyU3Lwf17ZT+rySAKh7DrAfMjiDf3OP8x3nOYEIHw7G2TPV3jr0lBrdAPs0WWcaTF4CIyJdr7/Mq9pd9tA2ebHL+y1186uMgKykQx9jjV0/LSTyRdIlfU/JWhtjFi5DCoA8FxoRo+c09lCxI3l1fHMm9A0rJ4Y5geGZTGmJcDxIxbqPLMIPHlJ8W05kzrkZcwwZo9AMDX9G7M+LYu84yTuYaMRLq3kS8fibe2VBClFH879w4M3pnp4OY9t4P2M6lbL3TnYzakv+xRgeCrkqnA4HTQxJy4BWe5M7tR1R1hBl4KVy8CdV8p+9VREQ7V6Z/3LSpFVnEHrFMfDK/lbxHBZrp0blYKsXG5I0WR2RIWsPd2CxECgYGxvRhOWLXoawLZG8lcrs42x75BMFA0d4eSjD6FMX6QvoqpIQ6+/dMvpkflauVGGyKTn0wySZJ3KcrA=
 file: 
 - "Sebagomez.BitLyHelper.dll"
 - "Sebagomez.ShelltwitLib.dll"
 - "Sebagomez.Shelltwit.dll"
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: sebagomez/shelltwit
