# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  buildConfiguration: 'Release'
  dockerId: 'sebagomez'

steps:
- script: dotnet build --configuration $(buildConfiguration) ./shelltwit.sln
  displayName: 'dotnet build'
- script: dotnet publish --configuration $(buildConfiguration) -o ../Docker/bin --no-build ./shelltwit.sln
  displayName: 'dotnet publish'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.SourcesDirectory)/Docker' 
    artifactName: 'deploy' 