# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  buildConfiguration: 'Release'
  dockerId: 'sebagomez'

steps:
- script: dotnet build --configuration $(buildConfiguration) ./shelltwitcore_NOTESTS.sln
  displayName: 'dotnet build'
- script: dotnet publish --configuration $(buildConfiguration) -o ../../Docker/bin --no-build ./shelltwitcore_NOTESTS.sln
  displayName: 'dotnet publish'
#- script: docker build --build-arg BUILD=$(build.buildNumber) -t $(dockerId)/azurestorageexplorer:$(build.buildNumber) .
#  workingDirectory: $(build.SourcesDirectory)/Docker
#  displayName: 'docker build'
#- script: docker tag $(dockerId)/azurestorageexplorer:$(build.buildNumber) $(dockerId)/azurestorageexplorer
#  displayName: 'docker tag'
#- script: docker login -u $(dockerId) -p $(dockerPwd) 
#  displayName: 'docker login'
#- script: docker push $(dockerId)/azurestorageexplorer:$(build.buildNumber)
#  displayName: 'docker push'
#- script: docker push $(dockerId)/azurestorageexplorer
#  displayName: 'docker push latest'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.SourcesDirectory)/Docker' 
    artifactName: 'deploy' 