# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  buildConfiguration: 'Release'
  dockerId: 'sebagomez'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
    
  steps:
  - script: dotnet build --configuration $(buildConfiguration) ./shelltwit.sln
    displayName: 'dotnet build'
  - script: dotnet publish --configuration $(buildConfiguration) -o $(build.SourcesDirectory)/Docker/bin --no-build ./shelltwit.sln
    displayName: 'dotnet publish'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: '$file = "Docker/bin/Sebagomez.Shelltwit.dll"

$version = $(Get-Item $file).VersionInfo.ProductVersion

Write-Host $version

Set-Content "Docker/version.txt" "Shelltwit v$($version)"'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(build.SourcesDirectory)/Docker' 
      artifactName: 'deploy' 